apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-s-o-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k-s-o-openshift
  template:
    metadata:
      labels:
        name: k-s-o-openshift
    spec:
      serviceAccountName: k-s-o-openshift
      containers:
        - name: k-s-o-openshift
          # Replace this with the built image name
          image: docker.io/jcrossley3/knative-serving-openshift:dev
          imagePullPolicy: Always
          command:
          - k-s-o-openshift
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k-s-o-openshift"
