kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k-s-o-openshift
subjects:
- kind: ServiceAccount
  name: k-s-o-openshift
roleRef:
  kind: Role
  name: k-s-o-openshift
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k-s-o-openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k-s-o-openshift
subjects:
- kind: ServiceAccount
  name: k-s-o-openshift
  namespace: default
